# Production configuration for Railway deployment with Supabase
spring:
  datasource:
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

# Production CORS
cors:
  allowed-origins: 
    - ${FRONTEND_URL}
    - https://mtor-evolution.netlify.app
    - https://your-custom-domain.com

# Production logging
logging:
  level:
    com.mtor.evolution: INFO
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
    org.springframework.boot.autoconfigure: WARN