server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1

spring:
  application:
    name: mtor-evolution
  
  # Supabase PostgreSQL Configuration
  datasource:
    url: ${DATABASE_URL:postgresql://postgres:YOUR_PASSWORD@db.sexklcnutdnmrwvarlwk.supabase.co:5432/postgres}
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:YOUR_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  h2:
    console:
      enabled: false
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: ${SHOW_SQL:false}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:mtor-evolution-secret-key-2024-very-long-and-secure-key-for-jwt-tokens-supabase-integration}
  expiration: ${JWT_EXPIRATION:86400000} # 24 hours
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

# CORS Configuration
cors:
  allowed-origins: 
    - ${FRONTEND_URL:https://mtor-evolution.netlify.app}
    - https://localhost:5173
    - http://localhost:5173
    - https://localhost:3000
    - http://localhost:3000
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - PATCH
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Logging for production
logging:
  level:
    com.mtor.evolution: ${LOG_LEVEL:INFO}
    org.springframework.security: WARN
    org.springframework.web: WARN
    org.hibernate.SQL: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always